server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
 
spring:
 application:
  name: configserver
 cloud:
  config:
   server:
    git:
     uri: https://github.com/hanmangoud9/Config-server
     default-label: main
 security: 
   user: 
    name: admin
    password: ganesha9
    
   